version: '3'

services:
  nginx:
    restart: always
    build:
        context: ./nginx
        dockerfile: Dockerfile
    image: gilsonnf/nginx
    container_name: nginx
    networks:
      - desafio-fc2
    ports:
      - "8080:80"
    depends_on:  
      - nodeserver

  nodeserver:
    build:
      context: node
      dockerfile: Dockerfile
    image: gilsonnf/nodeserver
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://mysqldb:3306 -timeout 30s docker-entrypoint.sh
    networks:
      - desafio-fc2
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:  
      - mysqldb
    command: node index.js


  mysqldb: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysqldb
    restart: always
    tty: true

    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD

    networks:
      - desafio-fc2

networks:
  desafio-fc2:
    driver: bridge